### ISSUE TITLE
Support for dbt 1.0

### ISSUE THREAD

**Issue by danielefrigo** [chop-analytics/dbt-netezza#6]
Do you have any plan to support dbt 1.0?

**Comment by VersusFacit** [comment]
Even if there isn't a plan, I'm kind of curious about this. I do adapters work at dbt Labs, and I'm curious about the engineering that'd need to be done here. 

If there's appetite from the owners to bring this up to date with 1.0.0, color me intrigued on the matter.

**Comment by cnolanminich** [comment]
@danielefrigo and @VersusFacit yes we are 💯 planning to get dbt-Netezza up to v1.0 for our own purposes .. our team hasn't had the bandwidth to keep up (and sorry about never reviewing / approving your changes @danielefrigo! Promise I'll take a look soon. 

@VersusFacit one challenge we've had is that we can't use the integration test suite, because our version of Netezza is not configured with schemas (I know, I know ..), so our testing efforts have been hampered and taken slowed down our ability to bring things up to 1.0. 

I was hoping we could tackle it this quarter, though that is fast approaching!

**Comment by danielefrigo** [comment]
@cnolanminich if useful, I did a quick & dirty test cloning the repo and changing only the dbt-core required version in setup.py.
I compiled my whole project (after changing just packages versions) and no errors.
I ran a single model and no errors again.
Next week I'll probably do more tests, but looks promising.

Do you expect some specific issue on your adapter when moving to dbt 1.0?

**Comment by cnolanminich** [comment]
I wasn't sure how much work it would or wouldn't be, I really haven't looked into the under the hood changes. 

That's very encouraging to hear! Maybe I'll do the same in a day or two and see what it looks like on my end as well.

**Comment by cnolanminich** [comment]
@danielefrigo just did some work this afternoon to test it out -- I did need to make a few changes, the biggest that involved solving a pesky bug in list_relations_without_caching() that caused issues with the Netezza quote policy.

Will post the update here in the next day or so, would love for you to take it for a spin as well!

**Comment by joemirizio** [comment]
Released in [v0.6.0](https://github.com/chop-analytics/dbt-netezza/releases/tag/v0.6.0)
